version: "3.8"

services:
  database:
    container_name: db
    image: postgres:13.4-alpine
    restart: always
    user: postgres 
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=library_db 
    ports:
      - 5432:5432 
    networks:
      - postgres

  api:
    build:
      context: ./library_back
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: api
    restart: unless-stopped
    volumes:
      - api:/var/lib/api
    depends_on:
      - database
    ports:
      - 8000:8000
    networks:
      - postgres

  web:
    build:
      context: ./library_front
      dockerfile: Dockerfile
    volumes:
      - front:/var/lib/front
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - postgres

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - web
    depends_on:
      - web
    networks:
      - postgres

volumes:
  pgdata: 
  api:
  front:
  server:

networks:
  postgres: