name: Continuos Integration

on:
  workflow_run: 
    workflows: ["Continuous Integration"]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        db: [postgres]
        python-version: [3.9]
        include:
          - db: postgres
            db_port: 5432
    services:
      postgres:
        image: postgres:13.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Run docker-compose
      working-directory: ./
      run: docker-compose build
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run docker-compose
        working-directory: ./
        run: docker-compose up -d 
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r ./library_back/requirements.txt
          chmod +x ./library_back/setup.sh && ./library_back/setup.sh
      - name: Run Tests
        working-directory: ./library_back
        run: |
          python3 manage.py test

        
  
