name: Continuos Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    environment: GCES
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Run docker-compose
      working-directory: ./
      run: docker-compose up -d 
      
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Docker Compose Up
        working-directory: ./
        run: docker-compose up -d 
      - name: Run Api tests
        working-directory: ./library_back
        run: python3 manage.py test
